name: Chaos Dataset
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # run once an hour

jobs:
  Chaos-run:
    runs-on: ubuntu-latest
    steps:

    - name: Install Git LFS
      run: |
        sudo apt-get install -y git-lfs
        git lfs install

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true

    - name: Run chaos
      run: |
        chmod +x data/chaos.sh
        cd data
        ./chaos.sh
        cd ..

    - name: Track large files
      run: |
        if [ -f data/alltargets.txt ]; then
          git lfs track "data/alltargets.txt"
          git add .gitattributes
          git rm --cached data/alltargets.txt || true
          git add data/alltargets.txt
        fi

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update Chaos dataset" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
