name: Chaos Dataset
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # run once an hour

jobs:
  Chaos-run:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Run chaos
      run: |
        chmod +x data/chaos.sh
        bash data/chaos.sh
    
    - name: Commit & Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main



